[package]
name = "tetris-rust"
version = "0.1.0"
authors = ["murikarox <eksi@kth.se>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl = "0.3.6"
